/*
	**AQUI SE ENCONTRARAN LOS PROTOTYPOS DE LAS FUNCIONES QUE SE
	UTILIZARAN A LO LARGO DEL PROGRAMA
*/

#ifndef _FUNCIONES_GENERALES_H_
#define _FUNCIONES_GENERALES_H_
//MENU PRINCIPAL
void menu(char *bin);
//CON ESTA FUNCION AGREGAMOS EL GENERO AL TIPO DE ELEMENTO Q ESTEMOS CREANDO
int agregar_genero(char *str,int pos);
//CON ESTA FUNCION ARREGLAMOS LOS ESPACIOS INNECESARIOS
void arreglar_espacios(char *txt);
//CON ESTA FUNCION ARREGLAMOS EL SALTO DE LINEA DEL FGETS
void arreglar_fgets(char *txt);
#endif/*_FUNCIONES_GENERALES_H_*/
